package report

type TargetField struct {
	Cost                              float64 `json:"cost,omitempty"`                                   // 展现数据-消耗
	Show                              int64   `json:"show,omitempty"`                                   // 展现数据-展示数
	AvgShowCost                       float64 `json:"avg_show_cost,omitempty"`                          // 展现数据-平均千次展示费用。
	AvgClickCost                      float64 `json:"avg_click_cost,omitempty"`                         // 展现数据-平均点击单价
	Click                             int64   `json:"click,omitempty"`                                  // 展现数据-点击数。
	Ctr                               float64 `json:"ctr,omitempty"`                                    // 展现数据-点击率。
	Convert                           int64   `json:"convert,omitempty"`                                // 转化数据-转化数。
	ConvertCost                       float64 `json:"convert_cost,omitempty"`                           // 转化数据-转化成本。
	ConvertRate                       float64 `json:"convert_rate,omitempty"`                           // 转化数据-转化率。
	DeepConvert                       int64   `json:"deep_convert,omitempty"`                           // 转化数据-深度转化次数。
	DeepConvertCost                   float64 `json:"deep_convert_cost,omitempty"`                      // 转化数据-深度转化成本。
	DeepConvertRate                   float64 `json:"deep_convert_rate,omitempty"`                      // 转化数据-深度转化率。
	AttributionConvert                int64   `json:"attribution_convert,omitempty"`                    // 转化数据-转化数（计费时间）。
	AttributionConvertCost            float64 `json:"attribution_convert_cost,omitempty"`               // 转化数据-转化成本（计费时间）。
	AttributionDeepConvert            int64   `json:"attribution_deep_convert,omitempty"`               // 转化数据-深度转化数（计费时间）。
	AttributionDeepConvertCost        float64 `json:"attribution_deep_convert_cost,omitempty"`          // 转化数据-深度转化成本（计费时间）。
	DownloadStart                     int64   `json:"download_start,omitempty"`                         // 应用下载广告数据-安卓下载开始数。
	DownloadStartCost                 float64 `json:"download_start_cost,omitempty"`                    // 应用下载广告数据-安卓下载开始成本。
	DownloadStartRate                 float64 `json:"download_start_rate,omitempty"`                    // 应用下载广告数据-安卓下载开始率。
	DownloadFinish                    int64   `json:"download_finish,omitempty"`                        // 应用下载广告数据-安卓下载完成数。
	DownloadFinishCost                float64 `json:"download_finish_cost,omitempty"`                   // 应用下载广告数据-安卓下载完成成本。
	DownloadFinishRate                float64 `json:"download_finish_rate,omitempty"`                   // 应用下载广告数据-安卓下载完成率。
	InstallFinish                     int64   `json:"install_finish,omitempty"`                         // 应用下载广告数据-安卓安装完成数。
	InstallFinishCost                 float64 `json:"install_finish_cost,omitempty"`                    // 应用下载广告数据-安卓安装完成成本。
	InstallFinishRate                 float64 `json:"install_finish_rate,omitempty"`                    // 应用下载广告数据-安卓安装完成率。
	Active                            int64   `json:"active,omitempty"`                                 // 应用下载广告数据-激活数
	ActiveCost                        float64 `json:"active_cost,omitempty"`                            // 应用下载广告数据-激活成本。
	ActiveRate                        float64 `json:"active_rate,omitempty"`                            // 应用下载广告数据-激活率。
	Register                          int64   `json:"register,omitempty"`                               // 应用下载广告数据-注册数。
	ActiveRegisterCost                float64 `json:"active_register_cost,omitempty"`                   // 应用下载广告数据-注册成本。
	ActiveRegisterRate                float64 `json:"active_register_rate,omitempty"`                   // 应用下载广告数据-注册率。
	AttributionNextDayOpenCnt         int64   `json:"attribution_next_day_open_cnt,omitempty"`          // 应用下载广告数据-次留数。
	AttributionNextDayOpenCost        float64 `json:"attribution_next_open_cost,omitempty"`             // 应用下载广告数据-次留成本。
	AttributionNextDayOpenRate        float64 `json:"attribution_next_day_open_rate,omitempty"`         // 应用下载广告数据-次留率。
	NextDayOpen                       int64   `json:"next_day_open,omitempty"`                          // 应用下载广告数据-次留回传数。
	GameAddiction                     int64   `json:"game_addiction,omitempty"`                         // 应用下载广告数据-关键行为数。
	GameAddictionCost                 float64 `json:"game_addiction_cost,omitempty"`                    // 应用下载广告数据-关键行为成本。
	GameAddictionRate                 float64 `json:"game_addiction_rate,omitempty"`                    // 应用下载广告数据-关键行为率。
	PayCount                          int64   `json:"pay_count,omitempty"`                              // 应用下载广告数据-首次付费数。
	ActivePayCost                     float64 `json:"active_pay_cost,omitempty"`                        // 应用下载广告数据-首次付费成本。
	ActivePayRate                     float64 `json:"active_pay_rate,omitempty"`                        // 应用下载广告数据-首次付费率。
	GamePayCount                      int64   `json:"game_pay_count,omitempty"`                         // 应用下载广告数据-付费次数。
	GamePayCost                       float64 `json:"game_pay_cost,omitempty"`                          // 应用下载广告数据-付费成本。
	AttributionGamePay7dCount         int64   `json:"attribution_game_pay_7d_count,omitempty"`          // 应用下载广告数据-7日付费次数（激活时间）。
	AttributionGamePay7dCost          float64 `json:"attribution_game_pay_7d_cost,omitempty"`           // 应用下载广告数据-7日付费成本（激活时间）。
	AttributionActivePay7dPerCount    int64   `json:"attribution_active_pay_7d_per_count,omitempty"`    // 应用下载广告数据-7日人均付费次数（激活时间）。
	LoanCompletion                    float64 `json:"loan_completion,omitempty"`                        // 应用下载广告数据-完件数。
	LoanCompletionCost                float64 `json:"loan_completion_cost,omitempty"`                   // 应用下载广告数据-完件成本。
	LoanCompletionRate                float64 `json:"loan_completion_rate,omitempty"`                   // 应用下载广告数据-完件率。
	PreLoanCredit                     float64 `json:"pre_loan_credit,omitempty"`                        // 应用下载广告数据-预授信数。
	PreLoanCreditCost                 float64 `json:"pre_loan_credit_cost,omitempty"`                   // 应用下载广告数据-预授信成本。
	LoanCredit                        float64 `json:"loan_credit,omitempty"`                            // 应用下载广告数据-授信数
	LoanCreditCost                    float64 `json:"loan_credit_cost,omitempty"`                       // 应用下载广告数据-授信成本。
	LoanCreditRate                    float64 `json:"loan_credit_rate,omitempty"`                       // 应用下载广告数据-授信率。
	InAppUv                           int64   `json:"in_app_uv,omitempty"`                              // 应用下载广告数据-APP内访问。
	InAppDetailUv                     int64   `json:"in_app_detail_uv,omitempty"`                       // 应用下载广告数据-APP内访问详情页。
	InAppCart                         int64   `json:"in_app_cart,omitempty"`                            // 应用下载广告数据-APP内加入购物车。
	InAppPay                          int64   `json:"in_app_pay,omitempty"`                             // 应用下载广告数据-APP内付费。
	InAppOrder                        int64   `json:"in_app_order,omitempty"`                           // 应用下载广告数据-APP内下单。
	Phone                             int64   `json:"phone,omitempty"`                                  // 落地页及门店数据-点击电话按钮。
	Form                              int64   `json:"form,omitempty"`                                   // 落地页及门店数据-表单提交。
	MapSearch                         int64   `json:"map_search,omitempty"`                             // 落地页及门店数据-地图搜索。
	Button                            int64   `json:"button,omitempty"`                                 // 落地页及门店数据-按钮button。
	View                              int64   `json:"view,omitempty"`                                   // 落地页及门店数据-关键页面浏览。
	Download                          int64   `json:"download,omitempty"`                               // 落地页及门店数据-下载开始。
	QQ                                int64   `json:"qq,omitempty"`                                     // 落地页及门店数据-QQ咨询。
	Lottery                           int64   `json:"lottery,omitempty"`                                // 落地页及门店数据-抽奖。
	Vote                              int64   `json:"vote,omitempty"`                                   // 落地页及门店数据-投票。
	Message                           int64   `json:"message,omitempty"`                                // 落地页及门店数据-短信咨询。
	Redirect                          int64   `json:"redirect,omitempty"`                               // 落地页转化数据-页面跳转。
	Shopping                          int64   `json:"shopping,omitempty"`                               // 落地页转化数据-商品购买。
	Consult                           int64   `json:"consult,omitempty"`                                // 落地页转化数据-在线咨询。
	Wechat                            int64   `json:"wechat,omitempty"`                                 // 落地页转化数据-微信复制。
	WechatLoginCount                  int64   `json:"wechat_login_count,omitempty"`                     // 落地页及门店数据-微信内注册数。
	AttributionWechatLogin30dCount    int64   `json:"attribution_wechat_login_30d_count,omitempty"`     // 落地页及门店数据-微信内注册数(计费时间)。
	WechatLoginCost                   float64 `json:"wechat_login_cost,omitempty"`                      // 落地页及门店数据-微信内注册成本。
	AttributionWechatLogin30Cost      float64 `json:"attribution_wechat_login_30d_cost,omitempty"`      // 落地页及门店数据-微信内注册成本(计费时间)。
	WechatFirstPayCount               int64   `json:"wechat_first_pay_count,omitempty"`                 // 落地页及门店数据-微信内首次付费数。
	AttributionWechatFirstPay30dCount float64 `json:"attribution_wechat_first_pay_30d_count,omitempty"` // 落地页及门店数据-微信内首次付费数(计费时间)。
	WechatFirstPayCost                float64 `json:"wechat_first_pay_cost,omitempty"`                  // 落地页及门店数据-微信内首次付费成本。
	AttributionWechatFirstPay30dCost  float64 `json:"attribution_wechat_first_pay_30d_cost,omitempty"`  // 落地页及门店数据-微信内首次付费成本(计费时间)。
	WechatFirstPayRate                float64 `json:"wechat_first_pay_rate,omitempty"`                  // 落地页及门店数据-微信内首次付费率。
	AttributionWechatFirstPay30dRate  float64 `json:"attribution_wechat_first_pay_30d_rate,omitempty"`  // 落地页及门店数据-微信内首次付费率(计费时间)。
	WechatPayAmount                   float64 `json:"wechat_pay_amount,omitempty"`                      // 落地页及门店数据-微信内首次付费金额。
	AttributionWechatPay30dAmount     float64 `json:"attribution_wechat_pay_30d_amount,omitempty"`      // 落地页及门店数据-微信内首次付费金额(计费时间)。
	AttributionWechatPay30dRoi        float64 `json:"attribution_wechat_pay_30d_roi,omitempty"`         // 落地页及门店数据-微信内首次付费ROI。
	PhoneConnect                      int64   `json:"phone_connect,omitempty"`                          // 落地页转化数据-智能电话-确认接通。
	PhoneConfirm                      int64   `json:"phone_confirm,omitempty"`                          // 落地页转化数据-智能电话-确认拨打。
	PhoneEffective                    int64   `json:"phone_effective,omitempty"`                        // 落地页及门店数据-智能电话-有效接通。
	ConsultEffective                  int64   `json:"consult_effective,omitempty"`                      // 落地页转化数据-有效咨询。
	Coupon                            int64   `json:"coupon,omitempty"`                                 // 落地页转化数据-建站卡券领取。
	CouponSinglePage                  int64   `json:"coupon_single_page,omitempty"`                     // 落地页转化数据-卡券页领取。
	RedirectToShop                    int64   `json:"redirect_to_shop,omitempty"`                       // 落地页及门店数据-调起店铺。
	PoiAddressClick                   int64   `json:"poi_address_click,omitempty"`                      // 落地页及门店数据-查看店铺地址。
	PoiCollect                        int64   `json:"poi_collect,omitempty"`                            // 落地页及门店数据-店铺收藏。
	LubanOrderCnt                     int64   `json:"luban_order_cnt,omitempty"`                        // 落地页及门店数据-鲁班订单量。
	LubanOrderStatAmount              float64 `json:"luban_order_stat_amount,omitempty"`                // 落地页及门店数据-鲁班订单金额。
	LubanOrderRoi                     float64 `json:"luban_order_roi,omitempty"`                        // 落地页及门店数据-鲁班ROI。
	LubanLiveEnterCnt                 int64   `json:"luban_live_enter_cnt,omitempty"`                   // 落地页及门店数据-直播间观看数。
	LubanWatchOneMinuteCount          int64   `json:"live_watch_one_minute_count,omitempty"`            // 落地页及门店数据-直播间超过1分钟观看数。
	LubanLiveFollowCnt                int64   `json:"luban_live_follow_cnt,omitempty"`                  // 落地页及门店数据-直播间关注数。
	LubanFansClubJoinCnt              int64   `json:"luban_fans_club_join_cnt,omitempty"`               // 落地页及门店数据-直播间加入粉丝团。
	LubanLiveCommentCnt               int64   `json:"luban_live_comment_cnt,omitempty"`                 // 落地页及门店数据-直播间评论数。
	LubanLiveShareCnt                 int64   `json:"luban_live_share_cnt,omitempty"`                   // 落地页及门店数据-直播间分享数。
	LubanLiveGiftCnt                  int64   `json:"luban_live_gift_cnt,omitempty"`                    // 落地页及门店数据-直播间打赏次数。
	LubanLiveGiftAmount               float64 `json:"luban_live_gift_amount,omitempty"`                 // 落地页及门店数据-直播间礼物总金额。
	LubanLiveSidecartClickCnt         int64   `json:"luban_live_slidecart_click_cnt,omitempty"`         // 落地页及门店数据-直播间查看购物车数。
	LubanLiveClickProductCnt          int64   `json:"luban_live_click_product_cnt,omitempty"`           // 落地页及门店数据-直播间点击商品数。
	LubanLivePayOrderCount            int64   `json:"luban_live_pay_order_count,omitempty"`             // 落地页及门店数据-直播间订单量。
	LubanLivePayOrderStatCost         float64 `json:"luban_live_pay_order_stat_cost,omitempty"`         // 落地页及门店数据-直播间订单金额。
	TotalPlay                         int64   `json:"total_play,omitempty"`                             // 视频数据-播放数。
	ValidPlay                         int64   `json:"valid_play,omitempty"`                             // 视频数据-有效播放数。
	ValidPlayCost                     float64 `json:"valid_play_cost,omitempty"`                        // 视频数据-有效播放成本。
	ValidPlayRate                     float64 `json:"valid_play_rate,omitempty"`                        // 视频数据-有效播放率。
	Play25FeedBreak                   int64   `json:"play_25_feed_break,omitempty"`                     // 视频数据-25%进度播放数。
	Play50FeedBreak                   int64   `json:"play_50_feed_break,omitempty"`                     // 视频数据-50%进度播放数。
	Play75FeedBreak                   int64   `json:"play_75_feed_break,omitempty"`                     // 视频数据-75%进度播放数。
	Play100FeedBreak                  int64   `json:"play_100_feed_break,omitempty"`                    // 视频数据-99%进度播放数。
	Play25FeedBreakRate               float64 `json:"play_25_feed_break_rate,omitempty"`                // 视频数据-25%进度播放率。
	Play50FeedBreakRate               float64 `json:"play_50_feed_break_rate,omitempty"`                // 视频数据-50%进度播放率。
	Play75FeedBreakRate               float64 `json:"play_75_feed_break_rate,omitempty"`                // 视频数据-75%进度播放率。
	Play100FeedBreakRate              float64 `json:"play_100_feed_break_rate,omitempty"`               // 视频数据-100%进度播放率。
	AveragePlayProgress               float64 `json:"average_play_progress,omitempty"`                  // 视频数据-平均播放进度。
	AveragePlayTimePerPlay            float64 `json:"average_play_time_per_play,omitempty"`             // 视频数据-平均单次播放时长,单位：秒。
	PlayOver                          int64   `json:"play_over,omitempty"`                              // 视频数据-播放完成数。
	PlayOverRate                      float64 `json:"play_over_rate,omitempty"`                         // 视频数据-播完率。
	WifiPlayRate                      float64 `json:"wifi_play_rate,omitempty"`                         // 视频数据-WiFi播放占比。
	WifiPlay                          int64   `json:"wifi_play,omitempty"`                              // 视频数据-WiFi播放量。
	CardShow                          int64   `json:"card_show,omitempty"`                              // 视频数据3秒卡片展现。
	PlayDuration10sRate               float64 `json:"play_duration_10s_rate,omitempty"`                 // 视频数据-10秒播放率。
	PlayDuration5sRate                float64 `json:"play_duration_5s_rate,omitempty"`                  // 视频数据-5秒播放率。
	PlayDuration3sRate                float64 `json:"play_duration_3s_rate,omitempty"`                  // 视频数据-3秒播放率。
	PlayDuration2sRate                float64 `json:"play_duration_2s_rate,omitempty"`                  // 视频数据-2秒播放率。
	AdvancedCreativePhoneClick        int64   `json:"advanced_creative_phone_click,omitempty"`          // 附加创意-附加创意电话按钮点击。
	AdvancedCreativeConsuelClick      int64   `json:"advanced_creative_counsel_click,omitempty"`        // 附加创意-附加创意在线咨询点击。
	AdvancedCreativeFormClick         int64   `json:"advanced_creative_form_click,omitempty"`           // 附加创意-附加创意表单按钮点击。
	AdvancedCreativeCouponAddition    int64   `json:"advanced_creative_coupon_addition,omitempty"`      // 附加创意-附加创意卡券领取。
	AdvancedCreativeFormSubmit        int64   `json:"advanced_creative_form_submit,omitempty"`          // 附加创意-附加创意表单提交。
	Share                             int64   `json:"share,omitempty"`                                  // 互动数据-分享数。
	Comment                           int64   `json:"comment,omitempty"`                                // 互动数据-评论数。
	Like                              int64   `json:"like,omitempty"`                                   // 互动数据-点赞数。
	Follow                            int64   `json:"follow,omitempty"`                                 // 互动数据-新增关注数。
	Dislike                           int64   `json:"dislike,omitempty"`                                // 互动数据-不感兴趣数。
	Report                            int64   `json:"report,omitempty"`                                 // 互动数据-举报数。
	MessageAction                     int64   `json:"message_action,omitempty"`                         // 互动数据-私信数。
	HomeVisited                       int64   `json:"home_visited,omitempty"`                           // 互动数据-主页访问量。
	IesChallengeClick                 int64   `json:"ies_challenge_click,omitempty"`                    // 互动数据-挑战赛查看数。
	IesMusicClick                     int64   `json:"ies_music_click,omitempty"`                        // 互动数据-音乐查看数。
	LocationClick                     int64   `json:"location_click,omitempty"`                         // 互动数据-POI点击数。
	ClickDownload                     int64   `json:"click_download,omitempty"`                         // 互动数据-主页下载链接点击量。
	ClickCallDy                       int64   `json:"click_call_dy,omitempty"`                          // 互动数据-主页内电话拨打点击量。
	ClickShopwindow                   int64   `json:"click_shopwindow,omitempty"`                       // 互动数据-主页商品橱窗访问量。
	ClickWebsite                      int64   `json:"click_website,omitempty"`                          // 互动数据-主页内落地页访问量（主页官网访问量）。
	ClickLandingPage                  int64   `json:"click_landing_page,omitempty"`                     // 互动数据-推广页访问量。
	InteractPerCost                   float64 `json:"interact_per_cost,omitempty"`                      // 互动数据-单次互动成本
	ConverShowRate                    float64 `json:"convert_show_rate,omitempty"`                      // 互动数据-转化展现率
	Cpc                               float64 `json:"cpc,omitempty"`                                    // Cost Per Click（每次点击的花费），按点击计费
	Cpm                               float64 `json:"cpm,omitempty"`                                    // Cost Per Mille（每千次曝光的花费），按展示计费
	Cpa                               float64 `json:"cpa,omitempty"`                                    // Cost Per Action（每次转化的花费），按转化计费
	SubmitCertificationCount          int64   `json:"submit_certification_count,omitempty"`             // 提交身份认证数
	ApprovalCount                     int64   `json:"approval_count,omitempty"`                         // 通过身份认证数
	FirstOrderCount                   int64   `json:"first_order_count,omitempty"`                      // 乘客首次下单数
	FirstRentalOrderCount             int64   `json:"first_rental_order_count,omitempty"`               // 司机首次完单数
	CommuteFirstPayCount              int64   `json:"commute_first_pay_count,omitempty"`                // 乘客首次支付数
}
